<?
	$TEMPLATE_PRODUCT_IBLOCK_ID = "167";
	$TEMPLATE_PRODUCT_PROPERTIES = "994, 995, 996, 997, 986, 989, 991, 993, 998, 988, 990, 992, 987, 985, 999, 1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012";
	$TEMPLATE_PRICE_CODES = "BASE, Хабаровскэнергосбыт";
	$TEMPLATE_THEME_NAME = "ultramarine";
	$TEMPLATE_BACKGROUND_NAME = "white";
	$TEMPLATE_HEADER = "header7";
	$TEMPLATE_SUBHEADER_COLOR = "default";
	$TEMPLATE_HEADER_COLOR = "theme";
	$TEMPLATE_HEADER_TYPE = "type1";
	$TEMPLATE_PANELS_COLOR = "white";
	$TEMPLATE_FOOTER_LINE_COLOR = "default";
	$TEMPLATE_FOOTER_VARIANT = "1";
	$TEMPLATE_USE_AUTO_WATERMARK = "N";
	$TEMPLATE_WATERMARK_TYPE = "image";
	$TEMPLATE_WATERMARK_SIZE = "big";
	$TEMPLATE_WATERMARK_FILL = "exact";
	$TEMPLATE_WATERMARK_POSITION = "topleft";
	$TEMPLATE_WATERMARK_FONT = "/home/bitrix/www/bitrix/templates/dps_dresscode_v1a/fonts/roboto/roboto-regular.ttf";
	$TEMPLATE_USE_AUTO_DEACTIVATE_PRODUCTS = "N";
	$TEMPLATE_USE_AUTO_SAVE_PRICE = "N";
	$TEMPLATE_USE_AUTO_BRAND = "N";
	$TEMPLATE_BRAND_IBLOCK_ID = "34";
	$TEMPLATE_USE_AUTO_COLLECTION = "N";
	$TEMPLATE_COLLECTION_IBLOCK_ID = "34";
?>